name: django app


on:
 push:
   branches:
     - developer


jobs:
- job:
    - name: Checkout
      uses: actions/checkout@v4.1.7
    
    - name: Docker Buildx Bake
      uses: docker/bake-action@v5.4.0
            
            